WIP
Signed-off-by: jamshale <jamiehalebc@gmail.com>

diff --git a/.github/workflows/bdd-interop-tests.yml b/.github/workflows/bdd-interop-tests.yml
--- a/.github/workflows/bdd-interop-tests.yml
+++ b/.github/workflows/bdd-interop-tests.yml
@@ -115,10 +115,10 @@ jobs:
         if: (steps.check_if_release.outputs.is_release != 'true' && github.event_name == 'pull_request' && steps.check-if-src-changed.outputs.run_tests == 'false')
         run: |
           cd owl-agent-test-harness 
-          output=$(NO_TTY=1 LEDGER_URL_CONFIG=http://test.bcovrin.vonx.io TAILS_SERVER_URL_CONFIG=https://tails.vonx.io ./manage run -d acapy-main -t @critical -t ~@wip -t ~@T004-RFC0211 -t ~@DidMethod_orb -t ~@Transport_NoHttpOutbound -t ~@Indy -t ~@CredFormat_Indy)
+          result=$(NO_TTY=1 LEDGER_URL_CONFIG=http://test.bcovrin.vonx.io TAILS_SERVER_URL_CONFIG=https://tails.vonx.io ./manage run -d acapy-main -t @critical -t ~@wip -t ~@T004-RFC0211 -t ~@DidMethod_orb -t ~@Transport_NoHttpOutbound -t ~@Indy -t ~@CredFormat_Indy)
           {
             echo 'output<<EOF'
-            echo "$output"
+            echo "$result"
             echo 'EOF'
           } >> $GITHUB_ENV
       # - name: Run Release or Nightly Interop Tests Anoncreds
@@ -131,12 +131,17 @@ jobs:
         if: steps.check-if-src-changed.outputs.run_tests == 'false'
         run: |
           out="${{ steps.run-pr-interop-tests-anoncreds.outputs.output }}"
-          if [[ "$out" == *"Failing scenarios:"* ]]; then
-              echo "Tests failed"
-              exit 1
-          else
-              echo "Tests passed"
-              exit 0
+          echo "$out"
+          echo"---------------------------------"
+          if [ ! -z "$out" ]; then
+              echo "0000000000000000000000000000000000000"
+              if [[ "$out" == *"Failing scenarios:"* ]]; then
+                  echo "Tests failed"
+                  exit 1
+              else
+                  echo "Tests passed"
+                  exit 0
+              fi
           fi
 
         # out=${{join(steps.run-release-interop-tests-anoncreds.outputs.*, '\n')}}
