WIP
Signed-off-by: jamshale <jamiehalebc@gmail.com>

diff --git a/.github/workflows/bdd-interop-tests.yml b/.github/workflows/bdd-interop-tests.yml
--- a/.github/workflows/bdd-interop-tests.yml
+++ b/.github/workflows/bdd-interop-tests.yml
@@ -126,5 +126,11 @@ jobs:
         if: steps.check-if-src-changed.outputs.run_tests == 'false'
         run: |
           cd owl-agent-test-harness
-          cat output.txt
+          if grep -q "Failed scenarios" output.txt; then
+              echo "Tests failed"
+              exit 1
+          else
+              echo "Tests passed"
+              exit 0
+          fi
 
