WIP
Signed-off-by: jamshale <jamiehalebc@gmail.com>

diff --git a/.github/workflows/bdd-interop-tests.yml b/.github/workflows/bdd-interop-tests.yml
--- a/.github/workflows/bdd-interop-tests.yml
+++ b/.github/workflows/bdd-interop-tests.yml
@@ -74,34 +74,76 @@ jobs:
 
           cd owl-agent-test-harness
           ./manage build -a acapy-main
-      - name: Run PR Interop Tests
-        id: run-pr-interop-tests
-        if: (steps.check_if_release.outputs.is_release != 'true' && github.event_name == 'pull_request' && steps.check-if-src-changed.outputs.run_tests != 'false')
+      # - name: Run PR Interop Tests Indy
+      #   id: run-pr-interop-tests-indy
+      #   if: (steps.check_if_release.outputs.is_release != 'true' && github.event_name == 'pull_request' && steps.check-if-src-changed.outputs.run_tests == 'false')
+      #   run: |
+      #     cd owl-agent-test-harness
+      #     NO_TTY=1 LEDGER_URL_CONFIG=http://test.bcovrin.vonx.io TAILS_SERVER_URL_CONFIG=https://tails.vonx.io ./manage run -d acapy-main -t @critical -t ~@wip -t ~@T004-RFC0211 -t ~@DidMethod_orb -t ~@Transport_NoHttpOutbound -t ~@Anoncreds
+      # - name: Run Release or Nightly Interop Tests Indy
+      #   id: run-release-interop-tests-indy
+      #   if: (steps.check_if_release.outputs.is_release == 'true' || github.event_name == 'schedule' || github.event_name == 'workflow_dispatch' && steps.check-if-src-changed.outputs.run_tests == 'false')
+      #   run: |
+      #     cd owl-agent-test-harness
+      #     NO_TTY=1 LEDGER_URL_CONFIG=http://test.bcovrin.vonx.io TAILS_SERVER_URL_CONFIG=https://tails.vonx.io ./manage run -d acapy-main -t @AcceptanceTest -t ~@wip -t ~@T004-RFC0211 -t ~@DidMethod_orb -t ~@Transport_NoHttpOutbound -t ~@Anoncreds
+      # - name: Check If Tests Failed
+      #   if: steps.check-if-src-changed.outputs.run_tests == 'false'
+      #   run: |
+      #     out=${{join(steps.run-pr-interop-tests-indy.outputs.*, '\n')}}
+      #     if [ ! -z "$out" ]; then
+      #         if [[ "$out" == *"Failing scenarios:"* ]]; then
+      #             echo "Tests failed"
+      #             exit 1
+      #         else
+      #             echo "Tests passed"
+      #             exit 0
+      #         fi
+      #     fi
+
+      #     out=${{join(steps.run-release-interop-tests-indy.outputs.*, '\n')}}
+      #     if [ ! -z "$out" ]; then
+      #         if [[ "$out" == *"Failing scenarios:"* ]]; then
+      #             echo "Tests failed"
+      #             exit 1
+      #         else
+      #             echo "Tests passed"
+      #             exit 0
+      #         fi
+      #     fi
+      - name: Run PR Interop Tests Anoncreds
+        id: run-pr-interop-tests-anoncreds
+        if: (steps.check_if_release.outputs.is_release != 'true' && github.event_name == 'pull_request' && steps.check-if-src-changed.outputs.run_tests == 'false')
         run: |
           cd owl-agent-test-harness
-          NO_TTY=1 LEDGER_URL_CONFIG=http://test.bcovrin.vonx.io TAILS_SERVER_URL_CONFIG=https://tails.vonx.io ./manage run -d acapy-main -t @critical -t ~@wip -t ~@T004-RFC0211 -t ~@DidMethod_orb -t ~@Transport_NoHttpOutbound -t ~@Anoncreds
-      - name: Run Release or Nightly Interop Tests
-        id: run-release-interop-tests
-        if: (steps.check_if_release.outputs.is_release == 'true' || github.event_name == 'schedule' || github.event_name == 'workflow_dispatch' && steps.check-if-src-changed.outputs.run_tests != 'false')
+          NO_TTY=1 LEDGER_URL_CONFIG=http://test.bcovrin.vonx.io TAILS_SERVER_URL_CONFIG=https://tails.vonx.io ./manage run -d acapy-main -t @critical -t ~@wip -t ~@T004-RFC0211 -t ~@DidMethod_orb -t ~@Transport_NoHttpOutbound -t ~@Indy -t ~@CredFormat_Indy
+      - name: Run Release or Nightly Interop Tests Anoncreds
+        id: run-release-interop-tests-anoncreds
+        if: (steps.check_if_release.outputs.is_release == 'true' || github.event_name == 'schedule' || github.event_name == 'workflow_dispatch' && steps.check-if-src-changed.outputs.run_tests == 'false')
         run: |
           cd owl-agent-test-harness
-          NO_TTY=1 LEDGER_URL_CONFIG=http://test.bcovrin.vonx.io TAILS_SERVER_URL_CONFIG=https://tails.vonx.io ./manage run -d acapy-main -t @AcceptanceTest -t ~@wip -t ~@T004-RFC0211 -t ~@DidMethod_orb -t ~@Transport_NoHttpOutbound -t ~@Anoncreds
+          NO_TTY=1 LEDGER_URL_CONFIG=http://test.bcovrin.vonx.io TAILS_SERVER_URL_CONFIG=https://tails.vonx.io ./manage run -d acapy-main -t @AcceptanceTest -t ~@wip -t ~@T004-RFC0211 -t ~@DidMethod_orb -t ~@Transport_NoHttpOutbound -t ~@Indy -t ~@CredFormat_Indy
       - name: Check If Tests Failed
         if: steps.check-if-src-changed.outputs.run_tests != 'false'
         run: |
-          out = ${{join(steps.run-pr-interop-tests.outputs.*, '\n')}}
+          out=${{join(steps.run-pr-interop-tests-anoncreds.outputs.*, '\n')}}
           if [ ! -z "$out" ]; then
-            if "$out" | grep -q "Failing scenarios:"; then
-              echo "Tests failed"
-              exit 1
-            fi
+              if [[ "$out" == *"Failing scenarios:"* ]]; then
+                  echo "Tests failed"
+                  exit 1
+              else
+                  echo "Tests passed"
+                  exit 0
+              fi
           fi
 
-          out = ${{join(steps.run-pr-interop-tests.outputs.*, '\n')}}
+          out=${{join(steps.run-release-interop-tests-anoncreds.outputs.*, '\n')}}
           if [ ! -z "$out" ]; then
-            if "$out" | grep -q "Failing scenarios:"; then
-              echo "Tests failed"
-              exit 1
-            fi
+              if [[ "$out" == *"Failing scenarios:"* ]]; then
+                  echo "Tests failed"
+                  exit 1
+              else
+                  echo "Tests passed"
+                  exit 0
+              fi
           fi
 
