WIP
Signed-off-by: jamshale <jamiehalebc@gmail.com>

diff --git a/.github/workflows/bdd-interop-tests.yml b/.github/workflows/bdd-interop-tests.yml
--- a/.github/workflows/bdd-interop-tests.yml
+++ b/.github/workflows/bdd-interop-tests.yml
@@ -125,16 +125,17 @@ jobs:
       - name: Check If Tests Failed
         if: steps.check-if-src-changed.outputs.run_tests == 'false'
         run: |
-          out=${{ steps.run-pr-interop-tests-anoncreds.outputs.stdout }}
-          if [ ! -z "$out" ]; then
-              if [[ "$out" == *"Failing scenarios:"* ]]; then
-                  echo "Tests failed"
-                  exit 1
-              else
-                  echo "Tests passed"
-                  exit 0
-              fi
-          fi
+          out="${{ steps.run-pr-interop-tests-anoncreds.outputs.stdout }}"
+          echo "$out"
+        # if [ ! -z "$out" ]; then
+        #     if [[ "$out" == *"Failing scenarios:"* ]]; then
+        #         echo "Tests failed"
+        #         exit 1
+        #     else
+        #         echo "Tests passed"
+        #         exit 0
+        #     fi
+        # fi
 
         # out=${{join(steps.run-release-interop-tests-anoncreds.outputs.*, '\n')}}
         # if [ ! -z "$out" ]; then
