WIP
Signed-off-by: jamshale <jamiehalebc@gmail.com>

diff --git a/.github/workflows/bdd-interop-tests.yml b/.github/workflows/bdd-interop-tests.yml
--- a/.github/workflows/bdd-interop-tests.yml
+++ b/.github/workflows/bdd-interop-tests.yml
@@ -17,9 +17,14 @@ defaults:
   run:
     shell: bash
 
+outputs:
+  run_tests: true
+
 jobs:
   test:
     runs-on: ubuntu-latest
+    outputs:
+      run_tests: ${{ steps.check-if-src-changed.outputs.run_tests }}
     # Run on openwallet-foundation and non-draft PRs or on non-PR events
     if: (github.repository == 'jamshale/acapy') && ((github.event_name == 'pull_request' && github.event.pull_request.draft == false) || (github.event_name != 'pull_request'))
     outputs:
@@ -115,17 +120,18 @@ jobs:
         if: (steps.check_if_release.outputs.is_release != 'true' && github.event_name == 'pull_request' && steps.check-if-src-changed.outputs.run_tests == 'false')
         run: |
           cd owl-agent-test-harness
-          NO_TTY=1 LEDGER_URL_CONFIG=http://test.bcovrin.vonx.io TAILS_SERVER_URL_CONFIG=https://tails.vonx.io ./manage run -d acapy-main -t @critical -t ~@wip -t ~@T004-RFC0211 -t ~@DidMethod_orb -t ~@Transport_NoHttpOutbound -t ~@Indy -t ~@CredFormat_Indy
-      - name: Run Release or Nightly Interop Tests Anoncreds
-        id: run-release-interop-tests-anoncreds
-        if: (steps.check_if_release.outputs.is_release == 'true' || github.event_name == 'schedule' || github.event_name == 'workflow_dispatch' && steps.check-if-src-changed.outputs.run_tests == 'false')
-        run: |
-          cd owl-agent-test-harness
-          NO_TTY=1 LEDGER_URL_CONFIG=http://test.bcovrin.vonx.io TAILS_SERVER_URL_CONFIG=https://tails.vonx.io ./manage run -d acapy-main -t @AcceptanceTest -t ~@wip -t ~@T004-RFC0211 -t ~@DidMethod_orb -t ~@Transport_NoHttpOutbound -t ~@Indy -t ~@CredFormat_Indy
+          output=$(NO_TTY=1 LEDGER_URL_CONFIG=http://test.bcovrin.vonx.io TAILS_SERVER_URL_CONFIG=https://tails.vonx.io ./manage run -d acapy-main -t @critical -t ~@wip -t ~@T004-RFC0211 -t ~@DidMethod_orb -t ~@Transport_NoHttpOutbound -t ~@Indy -t ~@CredFormat_Indy)
+          echo output="$output" >> $GITHUB_OUTPUT
+      # - name: Run Release or Nightly Interop Tests Anoncreds
+      #   id: run-release-interop-tests-anoncreds
+      #   if: (steps.check_if_release.outputs.is_release == 'true' || github.event_name == 'schedule' || github.event_name == 'workflow_dispatch' && steps.check-if-src-changed.outputs.run_tests == 'false')
+      #   run: |
+      #     cd owl-agent-test-harness
+      #     NO_TTY=1 LEDGER_URL_CONFIG=http://test.bcovrin.vonx.io TAILS_SERVER_URL_CONFIG=https://tails.vonx.io ./manage run -d acapy-main -t @AcceptanceTest -t ~@wip -t ~@T004-RFC0211 -t ~@DidMethod_orb -t ~@Transport_NoHttpOutbound -t ~@Indy -t ~@CredFormat_Indy
       - name: Check If Tests Failed
         if: steps.check-if-src-changed.outputs.run_tests != 'false'
         run: |
-          out=${{join(steps.run-pr-interop-tests-anoncreds.outputs.*, '\n')}}
+          out=${{steps.run-pr-interop-tests-anoncreds.outputs.output}}
           if [ ! -z "$out" ]; then
               if [[ "$out" == *"Failing scenarios:"* ]]; then
                   echo "Tests failed"
@@ -136,14 +142,14 @@ jobs:
               fi
           fi
 
-          out=${{join(steps.run-release-interop-tests-anoncreds.outputs.*, '\n')}}
-          if [ ! -z "$out" ]; then
-              if [[ "$out" == *"Failing scenarios:"* ]]; then
-                  echo "Tests failed"
-                  exit 1
-              else
-                  echo "Tests passed"
-                  exit 0
-              fi
-          fi
+        # out=${{join(steps.run-release-interop-tests-anoncreds.outputs.*, '\n')}}
+        # if [ ! -z "$out" ]; then
+        #     if [[ "$out" == *"Failing scenarios:"* ]]; then
+        #         echo "Tests failed"
+        #         exit 1
+        #     else
+        #         echo "Tests passed"
+        #         exit 0
+        #     fi
+        # fi
 
