Don't run from pytest
Signed-off-by: jamshale <jamiehalebc@gmail.com>

diff --git a/.github/workflows/scenario-integration-tests.yml b/.github/workflows/scenario-integration-tests.yml
--- a/.github/workflows/scenario-integration-tests.yml
+++ b/.github/workflows/scenario-integration-tests.yml
@@ -71,19 +71,14 @@ jobs:
             examples_dir=$(dirname "$examples_file")
             echo -e "\n🔎 Running scenario in: $examples_dir"
             cd "$examples_dir"
-
             docker compose build
-            docker compose up -d
-
-            echo "⏳ Waiting for example to finish..."
-            if ! docker compose run --rm controller; then
-              echo "❌ Example failed. Dumping logs..."
+            if ! docker compose up --exit-code-from controller; then
+              echo "❌ Tests failed for $dir - dumping logs:"
               docker compose logs
-              docker compose down --remove-orphans --timeout 5
+              docker compose down --remove-orphans
               exit 1
             fi
-
-            docker compose down --remove-orphans --timeout 5
-            echo "✅ Scenario passed"
+            echo "✅ Tests passed for $examples_dir"
+            docker compose down --remove-orphans
             cd - > /dev/null
           done
