Don't run from pytest
Signed-off-by: jamshale <jamiehalebc@gmail.com>

diff --git a/.github/workflows/scenario-integration-tests.yml b/.github/workflows/scenario-integration-tests.yml
--- a/.github/workflows/scenario-integration-tests.yml
+++ b/.github/workflows/scenario-integration-tests.yml
@@ -66,3 +66,21 @@ jobs:
           cd scenarios
           poetry install --no-root
           poetry run pytest -m examples
+        run: |
+          set -euo pipefail
+
+          for examples_file in $(find scenarios -type f -name 'examples'); do
+            examples_dir=$(dirname "$examples_file")
+            echo -e "\n🔎 Running scenario in: $examples_dir"
+            cd "$examples_dir"
+            docker compose build
+            if ! docker compose up --exit-code-from tests; then
+              echo "❌ Tests failed for $dir - dumping logs:"
+              docker compose logs
+              docker compose down --remove-orphans
+              exit 1
+            fi
+            echo "✅ Tests passed for $examples_dir"
+            docker compose down --remove-orphans
+            cd - > /dev/null
+          done
